### ISSUE TITLE
Project in IDE not loading files in the repository 

### ISSUE THREAD

**Issue by diepe28** [MobilizeNet/BlackDiamondStudio#6] opened 2022-02-04 22:41 UTC
**Describe the issue**
When I open my Migration Project project called "My tests project" in the IDE it does not load the files in the repository. I think this is because when I was creating it, I just entered the name of it, and that enabled me the "Open in IDE" button and I click on it. That was before I set up the "Connect Target Database" section and before I uploaded any .zip file in the "Convert Source Code" section. So, when I first clicked on the "Open in IDE" of course there was nothing in the repository because I had not set up any .zip file to be migrated. But then I did configure the Source Code zip file and I hit "Start Conversion" and everything seemed to go well (the progress was shown and everything was successfully completed). If I click on the "Open Repository" button, the page shows that in fact the files were migrated and everything, it shows the expected folders such as Logs, Reports, Sources, Target. But, every time I try to open the project in the IDE it does not load these files in the file explorer. I am attaching an image to show the problem. 

**To Reproduce**
1. Click on create new project.
2. Enter the name of the project.
3. Notice how the "Open in IDE" button becomes enabled, click on it. 
4. It will load the IDE but of course, there are no files yet in the repository. 
5. Go back to the page of the creation of the project. 
6. Skip the "Connect Target Database" section.
7. In the "Connect Source Code" section, choose Teradata as the Source Platform.
8. Enter the license.
9. Upload a sample .zip file with some .SQL files. 
10. Click on "Start Conversion" and wait for the process to finish. 
11. Once it finishes, click on the "OPEN IN IDE".
12. Notice how the file explorer in the IDE does not show all the files, that is the bug. 

**Expected behavior**
The IDE must show all the files in the repository. 

**Screenshots**

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Versión 98.0.4758.82 (Build oficial) (64 bits)

**Additional context**
![IDE Shows no files](https://user-images.githubusercontent.com/11539433/152610737-fa1d4776-b23a-4342-a9d0-f6b36bc8f4c9.png)

**Comment by AlonsoMontero** [comment] 2022-02-04 22:46
Thank for this report, @diepe28 . If you "pull" from the repo, do the changes appear in the IDE?

**Comment by rmelendez07** [comment] 2022-02-04 22:46
Hello, can you share a screenshot of the source control tab from IDE, please

**Comment by diepe28** [comment] 2022-02-04 22:54
Hey guys, this is how the source control tab looks in the IDE
![SourceControlTab](https://user-images.githubusercontent.com/11539433/152613862-77aed33a-243f-42a1-ac6d-b53978c1d53a.png)

Let me try to pull and see if that solves the issue.

**Comment by diepe28** [comment] 2022-02-04 22:55
Yes, if I click on "Pull" the file explorer is refreshed and all the files are shown as expected.

**Comment by AlonsoMontero** [comment] 2022-02-04 23:20
Thanks! This is the expected behavior right now, since the IDE does not have auto fetch enabled. We will consider enabling it so that this behavior is more user-friendly.

**Comment by AlonsoMontero** [comment] 2022-02-04 23:24
I am closing this since this is currently the expected behavior.

**Comment by AlonsoMontero** [comment] 2022-02-04 23:24
I am closing this since this is currently the expected behavior.

**Comment by diepe28** [comment] 2022-02-05 00:20
I would argue that at least the Source Control tab should have let the user know that there were changes to be pulled because there was no indication of that.

**Closed** 2022-07-12 20:10 UTC
